FROM php:8.1-apache-buster
COPY ./ /var/www/html/
RUN apt-get update;
RUN apt-get install -y libzip-dev;
RUN docker-php-ext-install zip pdo_mysql mysqli
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
COPY ./docker_config/web/web_cloud_build.conf /etc/apache2/sites-available/web.conf
RUN a2enmod rewrite
RUN a2ensite web
RUN a2dissite 000-default
RUN mkdir -p /var/www/html/laravel9/public
RUN mkdir -p /var/www/html/docker_config/web/logs/
RUN apachectl configtest
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
RUN cp /var/www/html/laravel9/.env.example /var/www/html/laravel9/.env
WORKDIR /var/www/html/laravel9/
RUN composer install
ENTRYPOINT /bin/bash
CMD "-c \"chmod -R 777 /var/www/html/laravel9 && apache2 -D FOREGROUND\""

